add doc for useTimeout
siberiacancode/reactuse pull request #15
Opened 2024-05-19 14:22 UTC by Alhymalhy

2024-05-20 15:14 UTC, crashmax-dev commented on src/hooks/useTimeout/useTimeout.ts
> + * @return {UseTimeoutReturn} An object with a `ready` boolean state value and a `clear` function to clear timeout.
```suggestion
 * @return {UseTimeoutReturn} An object with a `ready` boolean state value and a `clear` function to clear timeout.
 *
 * @example
 * const { clear, ready } = useTimeout(() => {}, 5000)
```

2024-05-20 15:15 UTC, crashmax-dev commented on docs/functions/hooks/useTimeout.md
useTimeout.md удалить

2024-05-20 15:16 UTC, crashmax-dev requested changes
@Alhymalhy после этого обнови ветку из main и проверь работу доки

2024-05-22 21:11 UTC, Alhymalhy commented
@crashmax-dev `No content found for useTimeout` :(

2024-05-25 18:56 UTC, merged