[feat:] useStopwatch 💪🏼
siberiacancode/reactuse pull request #172
Opened 2024-06-18 08:24 UTC by kvartycs

2024-06-23 06:54 UTC, debabin requested changes

2024-06-23 06:54 UTC, debabin commented on src/hooks/useStopwatch/useStopwatch.ts
> +export const useStopwatch = (autoStart: boolean = false): UseStopwatchReturn => {
нужно сделать форму параметров вот такой useStopwatch({enabled?: boolean, intitialTime: number }) | useStopwatch(intitialTime: number), короче говоря сделать возможность прокидывать default время + нагрузить функции, чтобы было удобнее пользоваться и не писать object всегда ради поля intitialTime

2024-06-23 06:54 UTC, debabin commented on src/hooks/useStopwatch/useStopwatch.ts
> +
нужно добавить в time count: 0 и работать уже с ним и получится, что-то типо такого 

```tsx
setTime((prevTime) => {
    prevTime.count++

     if (prevTime.count == 100) { 
            prevTime.second++; 
            prevTime.count = 0; 
        } 
  
        if (prevTime.second == 60) { 
            prevTime.minute++; 
            prevTime.second = 0; 
        } 
...
    return prevTime
```
Так код станет более линейным и читаемым

2024-06-23 06:54 UTC, debabin commented on src/hooks/useStopwatch/useStopwatch.ts
> +    )}:${addLeadingZero(time.minutes)}:${addLeadingZero(time.seconds)}`,
Это ответственность пользователя, удалить из хука

2024-06-23 06:54 UTC, debabin commented on src/hooks/useStopwatch/useStopwatch.ts
> +    isOver,
paused, over

2024-06-23 06:54 UTC, debabin commented on src/hooks/useStopwatch/useStopwatch.ts
> +    seconds: time.seconds,
...time

2024-06-23 06:54 UTC, debabin commented on src/hooks/useStopwatch/useStopwatch.ts
> +    }
toggle: (prevPause) => setPaused(!prevPause);

2024-06-23 06:54 UTC, debabin commented on src/hooks/useStopwatch/useStopwatch.ts
> +    elapsedSeconds: time.days * 86400 + time.hours * 3600 + time.minutes * 60 + time.seconds,
тут можно будет это удалить, ведь будет теперь count

2024-06-25 13:09 UTC, kvartycs commented on src/hooks/useStopwatch/useStopwatch.ts
> +};
исходя из комментария ниже в ней нет необходимости, удалено

В будущем при необходимости можно добавить

2024-06-30 08:20 UTC, merged